[workspace]
resolver = "3"
members = [
    "just_template",
    "just_template_macros",
]

[workspace.package]
version = "0.2.0"
description = "A tool for code gen via templatese"
authors = ["Weicao-CatilGrass <catil_grass@qq.com>"]
edition = "2024"

homepage = "https://github.com/catilgrass/just_template"
repository = "https://github.com/catilgrass/just_template"
license = "MIT OR Apache-2.0"
keywords = ["template", "code-generation", "codegen"]
categories = ["template-engine"]

[workspace.dependencies]
just_template = { path = "just_template" }
just_template_macros = "0.2.0"
# just_template_macros = { path = "just_template_macros" }
