[package]
name = "just_template"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

readme = "README.md"
documentation = "https://docs.rs/just_template"

[dependencies]
just_template_macros.workspace = true
just_fmt = "0.1.2"
